export const americanCinnamonRolls = {
  name: 'American Cinnamon Rolls',
  param: 'american-cinnamon-rolls',
  recipeImage: 'assets/images/american-cinnamon-rolls.jpg',
  star: false,
  introText: 'Cinnamon rolls, but stickier, messier, squeezed together, and topped with a glaze.',
  description:
    'Mde with a fluffy dough, filled with a sweet cinnamon-sugar mixture, and baked to golden perfection. For these you might want to bring a fork or be prepared to get sticky fingers.',
  category: 'dessert',
  tags: {
    quick: false,
    easy: false,
    temperature: '180',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Yeast',
      amount: 6,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 40,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bread flour',
      amount: 300,
      unit: 'g',
      flex: 'Regular flour.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter (for filling)',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon (for filling)',
      amount: 2,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar (for filling)',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Icing sugar (for glaze)',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream cheese (for glaze)',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Warm the milk to lukewarm temperature (36-39°C), and dissolve the yeast in it. Let it sit for 5–10 minutes until frothy.',
    'In a mixing bowl, combine the flour, sugar, baking powder, and salt. Add the yeast mixture and melted butter. Mix until a dough forms. Let it rise in a warm place for 1–1.5 hours, or until doubled in size.',
    'Knead the dough on a floured surface for 8–10 minutes until smooth and elastic.',
    'In a small bowl, prepare the filling by combining softened butter, cinnamon, and sugar until it forms a spreadable mixture.',
    'Roll out the dough on a floured surface into a rectangle about 1 cm thick. Spread the filling evenly over the dough.',
    'Starting from one long edge, roll the dough tightly into a log. Slice the log into 8–10 rolls and place them in a greased baking dish or a dish with parchement paper.',
    'Cover the rolls and let them rise for another 30–45 minutes, or until puffy.',
    'Preheat the oven to 180°C. Glaze the rolls with melted butter. Bake the cinnamon rolls for 30 minutes, or until golden brown.',
    'Let the rolls cool slightly before applying the glaze and serving.',
  ],
  notes:
    'Instead of a cream cheese glaze, top these rolls with a simple glaze made of powdered sugar and milk or a juice. Store any leftovers in an airtight container for up to 2 days, and reheat for a few seconds in the microwave for the best texture.',
};
