export const basilStrawberryMuffins = {
  name: 'Basil Strawberry Muffins',
  param: 'basil-strawberry-muffins',
  recipeImage: 'assets/images/basil-strawberry-muffins.png',
  star: false,
  introText:
    'These unique basil strawberry muffins combine the sweet, juicy flavor of strawberries with the aromatic freshness of basil.',
  description:
    'The strawberries add natural sweetness and moisture, while the basil provides a unique herbal note that elevates these muffins to something special. Perfect for breakfast or a snack, a twist on the classic strawberry muffin.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Strawberries',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Basil',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Balsamic vinegar',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line muffin tins with paper liners.',
    'Chop the strawberries into fine cubes. Pick your basil leaves.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, black pepper, and the white sugar.',
    'In a separate bowl, combine the strawberries, basil, brown sugar, oil, milk, and balsamic vinegar. Whisk until well mixed. Chop up or slice the basil if desired.',
    'Add the wet and dry ingredients together, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 18 minutes if using small muffin ramekins, 20-23 min if using large muffin ramekins, or until a toothpick inserted into the center comes out clean.',
    'Allow the muffins to cool in the tin for 20 minutes before serving.',
  ],
  notes:
    'Fresh or frozen strawberries can be used. Adjust the amount of black pepper to your spice preference. Store in an airtight container at room temperature for up to 3 days, or refrigerate for longer freshness. Can also be frozen. Sprinkle sugar on top for a sweet, crusty surface.',
};
