export const blueberryYuzuMuffins = {
  name: 'Blueberry Yuzu Muffins',
  param: 'blueberry-yuzu-muffins',
  recipeImage: 'assets/images/blueberry-yuzu-muffins.jpg',
  star: false,
  introText:
    'These delightful muffins combine the sweetness of blueberries with the bright, citrusy flavor of yuzu. A perfect balance of fruity and tangy!',
  description:
    'These muffins feature fresh blueberries and aromatic yuzu juice for a unique citrus twist. The tender crumb and bursts of blueberry make them perfect for breakfast or as a special snack.',
  category: ['dessert', 'breakfast', 'snack'],
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 150,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yuzu juice',
      amount: 1,
      unit: 'tbsp',
      flex: 'Lemon or lime juice',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Blueberries',
      amount: 100,
      unit: 'g',
      flex: 'Fresh or frozen blueberries both work well',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, and salt. Mix well with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the milk, sugar, oil, and yuzu juice. Whisk until well combined.',
    'Add the dry ingredients to the wet ingredients, stirring until just combined. Do not overmix.',
    'Gently fold in the blueberries, being careful not to crush them.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 20 minutes if using small muffin liners, 22 minutes for larger muffin liners, or until a toothpick inserted into the center comes out clean.',
    'Allow the muffins to cool in the tin for 10 minutes before transferring to a wire rack.',
  ],
  notes:
    'Use salt according to your own taste, somewhere between 1/4 and 1/2 teaspoon. If using frozen blueberries, do not thaw them before adding to the batter to prevent bleeding. Store in an airtight container at room temperature for up to 2 days, or refrigerate for up to 5 days. These muffins freeze well. For extra citrus flavor, you can add yuzu zest to the batter.',
};
