export const breakBread = {
  name: 'Break Bread',
  param: 'break-bread',
  recipeImage: 'assets/images/break-bread.jpg',
  star: false,
  introText: 'Called "Break Bread" because it is meant to be shared with others.',
  description:
    'A soft and fluffy bread made with minimal ingredients and delivers maximum flavor. The addition of a touch of sugar and oil ensures a tender crumb and a golden crust.',
  category: 'bread',
  tags: {
    quick: false,
    easy: true,
    temperature: '220°C',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Yeast',
      amount: 25,
      unit: 'g',
      flex: '7g dried yeast',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 320,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Oil',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 420,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Warm the plant-based milk to about 40°C (lukewarm, not hot). Stir in the yeast and sugar.',
    'In a large mixing bowl, combine the flour and salt. Make a well in the center and pour in the yeast mixture and oil.',
    'Mix until the dough comes together, then transfer to a floured surface and knead for 8-10 minutes, or until the dough is smooth and elastic.',
    'Roll out the dough into a long roll, then divide it up into eight even pieces. Roll each piece to a ball and place it on a baking sheet lined with parchment paper or in a greased bread pan.',
    'Optionally dust some flour on top of the bread. Cover again and let it rise for another 30 minutes.',
    'Preheat the oven. Once the dough has risen, bake for 20 minutes.',
    'Allow the bread to cool on a wire rack before slicing and serving.',
  ],
  notes:
    'This bread is highly adaptable—you can add herbs, seeds, or even a touch of garlic powder to the dough for extra flavor. It also freezes well; slice and store in an airtight bag for up to a month.',
};
