export const chickpeaCurry = {
  name: 'Chickpea Curry',
  param: 'chickpea-curry',
  recipeImage: 'assets/images/chickpea-curry.jpg',
  star: false,
  introText: 'An easy chickpea curry that’s full of flavor, especially some hours after making it.',
  description:
    'Chickpea Curry is a delicious and satisfying dish made with chickpeas simmered in a spiced tomato sauce. It’s a one-pot meal that’s easy to prepare and can be served with rice or bread. The combination of spices creates a warm and comforting flavor, making it a favorite for many.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Tomatoes',
      amount: 400,
      unit: 'g',
      flex: 'Canned whole, fresh, crushed, puréed.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 25,
      unit: 'g',
      flex: 'Vegetable oil.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 2,
      unit: '',
      flex: 'Any onion works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger, grated',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 2,
      unit: 'cube',
      flex: '1 tsp salt',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Any pepper works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked paprika',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Turmeric',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gingerbread spice',
      amount: 2,
      unit: 'tsp',
      flex: '0.5 tsp cinnamon, 0.5 tsp nutmeg, 0.5 tsp allspice, 0.5 tsp cloves.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato paste',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bread',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Drain the chickpeas. Finely chop the onions, mince the garlic, and grate the ginger. Roughly chop the cilantro (if using).',
    'Melt the butter in a large pot over medium heat. Add the onions and cook 5–7 minutes until soft and lightly golden.',
    'Add garlic, ginger, and spices: Stir in the garlic, grated ginger, cumin, smoked paprika, turmeric, white pepper, and gingerbread spice. Cook 30–60 seconds until fragrant.',
    'Add the tomato paste and sugar. Cook 1–2 minutes to caramelize slightly, then add the tomatoes and ketchup. Crumble in the bouillon cubes (or use salt to taste). If very thick, add a splash of water.',
    'Bring to a gentle simmer and cook 8–10 minutes, stirring occasionally and breaking up the tomatoes so the sauce becomes smooth and glossy.',
    'Stir in the chickpeas and simmer another 8–10 minutes until heated through and the flavors meld.',
    'Stir in cilantro (if using). Taste and adjust seasoning (salt/pepper/sugar) to balance acidity and heat.',
    'Serve warm with bread on the side.',
  ],
  notes:
    'Garnish with extra cilantro, perhaps a drizzle of coconut milk or cream, and serve with bread.',
};
