export const chocolateChipCookies = {
  name: 'Chocolate Chip Cookies',
  param: 'chocolate-chip-cookies',
  recipeImage: 'assets/images/chocolate-chip-cookies.jpg',
  star: false,
  introText:
    'Indulge in the timeless delight of warm, gooey chocolate chip cookies. Perfectly chewy with crispy edges, they’re the ultimate treat for any occasion.',
  description:
    'These Levain-style chocolate chip cookies are a NYC classic. With their crisp edges and soft, chewy centers, they’re the perfect balance of sweet and salty. This recipe uses simple ingredients and straightforward techniques to create the ultimate homemade cookie.',
  category: 'dessert',
  tags: {
    quick: false,
    easy: true,
    temperature: '225',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Butter',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Plant milk',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vanilla extract',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Corn starch',
      amount: 1,
      unit: 'tbsp',
      flex: 'Tapioca starch, potato starch, arrowroot powder.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark chocolate',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat your oven to 225°C (450°F) fan and line a baking sheet with parchment paper.',
    'In a mixing bowl, cream together softened butter and brown sugar until smooth and fluffy.',
    'Stir in the milk and vanilla extract until fully combined.',
    'In a separate bowl, whisk together the flour, starch, baking soda, and salt.',
    'Add the dry and wet ingredients together, mix until a soft dough forms.',
    'Fold in the chocolate chips until evenly distributed.',
    'Scoop the dough onto the prepared baking sheet, spacing each cookie about a couple centimeters apart.',
    'Bake for 8-10 minutes, or until the surface looks golden brown.',
    'Let the cookies cool on the baking sheet for 10 minutes before eating.',
  ],
  notes:
    'For extra indulgence, sprinkle a pinch of sea salt on top of the cookies before or after baking. You can also experiment with add-ins like chopped nuts, dried fruits, or different types of chocolate. Keep the scoops rugged for a rustic look.',
};
