export const cremeBrulee = {
  name: 'Crème Brûlée',
  param: 'creme-brulee',
  recipeImage: 'assets/images/creme-brulee.jpg',
  star: false,
  introText: 'Indulge in this silky vegan crème brûlée, a plant-based twist on the classic French dessert.',
  description:
    'This vegan crème brûlée offers a rich and creamy custard base topped with a caramelized sugar crust. Perfect for a dinner party or an indulgent treat, it’s surprisingly easy to make and uses simple, pantry-friendly ingredients.',
  category: 'dessert',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Sugar',
      amount: 80,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Corn starch',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan butter',
      amount: 40,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Plant-based milk',
      amount: 400,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vanilla extract',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a bowl add the sugar, the vanilla, the corn starch, salt, the lemon juice, the almond milk, and stir well with a hand whisk for 1-2 minutes.',
    'Transfer to a pot over high heat and stir until the mixture thickens and starts boiling.',
    'Turn off the heat and add the margarine. Mix well until it melts.',
    'Divide the mixture among 6 ramekins and refrigerate for 2-3 hours.',
    'Sprinkle with 1-2 tablespoons granulated sugar and burn it with a kitchen torch until it is caramelized. Alternatively, put them in the oven, set to broiler, until the sugar melts and turns golden.',
  ],
  notes:
    'For best results, use a kitchen torch to caramelize the sugar for a perfectly even crust. This dessert can be made a day in advance, but caramelize the sugar right before serving to maintain the crisp texture.',
};
