export const crispyRiceSalad = {
  name: 'Crispy Rice Salad',
  param: 'crispy-rice-salad',
  recipeImage: 'assets/images/crispy-rice-salad.jpg',
  star: false,
  introText:
    'This crispy rice salad is a delightful mix of textures and flavors, perfect for a quick lunch or a refreshing side dish.',
  description:
    'Crispy rice forms the base of this vibrant salad, complemented by creamy avocado, crunchy cashews, and fresh vegetables. The zesty dressing brings it all together for a dish that’s both satisfying and nutritious. Perfect for any occasion, it’s as easy to make as it is delicious.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: '200',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Avocado',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bell pepper',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cucumber',
      amount: 0.25,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cashew nuts',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Edamame beans',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rice vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime juice',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat your oven to 200°C (400°F).',
    'Spread the cooked rice evenly onto a lined baking sheet. Drizzle with the vegetable oil and chili sauce, tossing gently to coat.',
    'Bake the rice for 40 minutes, stirring occasionally, until crispy and golden brown. Remove from the oven and let it cool slightly.',
    'While the rice is baking, prepare the vegetables: dice the avocado, bell pepper, and cucumber.',
    'In a small bowl, whisk together the light soy sauce, rice vinegar, grated ginger, sesame oil, brown sugar, and lime juice to make the dressing.',
    'In a large mixing bowl, combine the crispy rice, diced vegetables, cashew nuts, and edamame beans.',
    'Pour the dressing over the salad and toss gently to combine.',
    'Serve immediately or store in the fridge for up to one day.',
  ],
  notes:
    'For extra flavor, you can garnish the salad with chopped cilantro, sesame seeds, or a sprinkle of chili flakes. This salad works great as a standalone meal or a side dish for a larger spread.',
};
