export const crispyChiliOil = {
  name: 'Crispy Chili Oil',
  param: 'crispy-chili-oil',
  recipeImage: 'assets/images/crispy-chili-oil.jpg',
  star: false,
  introText:
    'This crispy chili oil is packed with bold flavors, combining aromatic spices and a fiery kick for a versatile condiment that enhances any dish.',
  description:
    'This homemade crispy chili oil brings together the deep flavors of roasted onion, garlic, and ginger with a satisfying crunch from sesame seeds. The perfect balance of heat and umami, this oil will elevate stir-fries, noodles, and rice bowls. Simple yet intensely flavorful, it’s a must-have addition to your pantry.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Fried shallots',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 2,
      unit: 'tbsp',
      flex: 'White or black sesame seeds can be used',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chinese 5 spice',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochujaru',
      amount: 0.5,
      unit: 'cup',
      flex: 'A different chili powder can be used, or a mix of several types',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Szechuan oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Rice vinegar',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a heatproof bowl, add the fried shallots, sugar, salt, garlic, sesame seeds, MSG, Chinese 5 spice, ginger, and gochujaru.',
    'In a small saucepan, heat the vegetable oil over medium heat until it reaches around 350°F (175°C). You’ll want it hot, but not smoking.',
    'Once the oil is heated, carefully pour it over the prepared ingredients in the bowl. The heat from the oil will release all the aromatics and infuse the oil with flavor.',
    'Stir in the Szechuan oil and rice vinegar to combine.',
    'Let the mixture cool completely before transferring it to a jar. Store in an airtight container in the refrigerator for up to 2 weeks.',
  ],
  notes:
    'For an extra kick, you can adjust the amount of gochujaru or add a bit more Szechuan oil. This chili oil is perfect as a drizzle over noodles, rice dishes, or even as a dipping sauce. No need to cook the aromatics in the oil directly—this method ensures the ingredients stay crispy and flavorful.',
};
