export const cupcakes = {
  name: 'Cupcakes',
  param: 'cupcakes',
  recipeImage: 'assets/images/cupcakes.jpg',
  star: false,
  introText:
    'These delightful cupcakes topped with silky Swiss meringue buttercream are perfect for celebrations or as a special treat. Light, fluffy, and beautifully frosted!',
  description:
    'Classic cupcakes with a tender crumb, topped with luxurious Swiss meringue buttercream. The cupcakes use a simple muffin base, while the frosting is made with aquafaba for a light and airy meringue that whips into a smooth, buttery finish.',
  category: 'dessert',
  tags: {
    quick: false,
    easy: false,
    temperature: '175',
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 150,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Aquafaba',
      amount: 160,
      unit: 'g',
      flex: 'Liquid from canned chickpeas',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Sugar (for buttercream)',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Butter, room temperature',
      amount: 400,
      unit: 'g',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Cream of tartar',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and the white sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the yogurt, brown sugar, oil, and milk. Whisk until smooth (but no worries if there are some brown sugar lumps, just leave them be).',
    'Add the dry ingredients to the wet ingredients, stirring until just combined. Do not overmix.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 20 minutes if using small cupcake liners, 22 minutes if using large cupcake liners, or until a toothpick inserted into the center comes out clean.',
    'Allow the cupcakes to cool completely in the tin before frosting.',
    'For the Swiss meringue buttercream: Combine aquafaba, 250g sugar, and cream of tartar (if using) in a heatproof bowl over a pot of simmering water (double boiler).',
    'Whisk constantly until the sugar has completely dissolved and the mixture reaches 160°F (71°C), about 5-7 minutes.',
    'Remove from heat and transfer to a stand mixer bowl. Whip on high speed until stiff peaks form and the bowl is cool to the touch, about 10-15 minutes.',
    'Reduce speed to medium and add the room temperature butter, one tablespoon at a time, mixing well after each addition.',
    'Once all butter is incorporated, increase speed to high and beat until smooth and fluffy, about 3-5 minutes. The mixture may look curdled at first but will come together.',
    'Pipe or spread the buttercream onto the cooled cupcakes.',
  ],
  notes:
    'Make sure the butter is at room temperature (not melted or cold) for the best texture. If the buttercream looks soupy, chill it briefly and re-whip. If it looks curdled, keep beating - it will come together. The buttercream can be flavored with vanilla extract, citrus zest, or other extracts. Store frosted cupcakes in an airtight container in the refrigerator for up to 3 days. Bring to room temperature before serving.',
};
