export const earlGreyHempCookies = {
  name: 'Earl Grey Hemp Cookies',
  param: 'earl-grey-hemp-cookies',
  recipeImage: 'assets/images/earl-grey-hemp-cookies.jpg',
  star: false,
  introText:
    'A fragrant twist on classic chocolate chip cookies, infused with aromatic Earl Grey tea and nutty hemp seeds for added texture and depth.',
  description:
    "These Levain-style cookies combine the beloved chewy centers and crisp edges of chocolate chip cookies with the floral notes of Earl Grey tea and the earthy crunch of hemp seeds. A unique, sophisticated treat that's as easy to make as the original.",
  category: 'dessert',
  tags: {
    quick: false,
    easy: true,
    temperature: '225',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Butter',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Plant milk',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Earl Grey',
      amount: 2,
      unit: 'bags',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Hemp seeds',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Corn starch',
      amount: 1,
      unit: 'tbsp',
      flex: 'Tapioca starch, potato starch, arrowroot powder.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark chocolate',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat your oven to 225°C (450°F) fan and line a baking sheet with parchment paper.',
    'Cut open the Earl Grey tea bags and empty the loose tea leaves into a small bowl. Discard the bags.',
    'In a mixing bowl, cream together softened butter and brown sugar until smooth and fluffy.',
    'Stir in the milk and vanilla extract until fully combined.',
    'In a separate bowl, whisk together the flour, starch, baking soda, salt, and Earl Grey tea leaves.',
    'Add the dry and wet ingredients together, mix until a soft dough forms.',
    'Fold in the chocolate chips and hemp seeds until evenly distributed.',
    'Scoop the dough onto the prepared baking sheet, spacing each cookie about a couple centimeters apart.',
    'Bake for 8-10 minutes, or until the surface looks golden brown.',
    'Let the cookies cool on the baking sheet for 10 minutes before eating.',
  ],
  notes:
    'Black sesame paste can be used instead of chocolate chips for a more earthy, nutty flavor that complements the Earl Grey and hemp seeds. Adjust the amount to your taste, starting with 2 tablespoons and adding more if desired.',
};
