export const gochujangNoodles = {
  name: 'Gochujang Noodles',
  param: 'gochujang-noodles',
  recipeImage: 'assets/images/gochujang-noodles.jpg',
  star: false,
  introText: 'Spicy and savory Korean-inspired noodles with a rich gochujang sauce.',
  description:
    'These gochujang noodles are a perfect fusion of Korean flavors with the convenience of ramen. The gochujang provides a deep, spicy-sweet heat while the butter adds richness. Combined with garlic, sesame oil, and soy sauce, this creates an incredibly flavorful and satisfying noodle dish.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Gochujang',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 5,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rice vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any vinegar works',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any sugar or sweetener',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ramen noodles',
      amount: 3,
      unit: 'packs',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions',
      amount: 2,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'In a large pan or wok, melt the butter over medium heat.',
    'Add the minced garlic and sauté for about 1 minute until fragrant.',
    'Add the gochujang, soy sauce, sesame oil, rice vinegar, and brown sugar to the pan. Stir well to combine.',
    'Add the noodles and water to the pan and cover with a lid for 5 minutes or until al dente. After that if the sauce is too thick, add some additional water.',
    'Remove from heat and garnish with chopped scallions and sesame seeds.',
  ],
  notes:
    'Adjust the amount of gochujang to your spice preference. You can add vegetables like bok choy, mushrooms, or carrots for extra nutrition. For protein, consider adding edamame beans or tofu.',
};
