export const gochujangTofuNoodles = {
  name: 'Gochujang Tofu Noodles',
  param: 'gochujang-tofu-noodles',
  recipeImage: 'assets/images/gochujang-noodles.jpg',
  star: false,
  introText: 'Smoky tofu, crisp bok choi, and a peanut-gochujang sauce sharpened with yuzu.',
  description:
    'A weeknight noodle bowl built around a no-cook sauce: gochujang for fermented heat, peanut butter for body, Maggi and light soy for depth, and yuzu juice to cut straight through the richness. Smoked tofu is seared until the edges crisp, bok choi goes into the noodle water for the last minute, and a splash of starchy pasta water pulls everything into a glossy sauce that clings to every strand. Roughly 20 minutes from pan to bowl.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Noodles',
      amount: 250,
      unit: 'g',
      flex: 'Wheat noodles, ramen, or udon.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked tofu',
      amount: 200,
      unit: 'g',
      flex: 'Firm tofu, pressed and seared.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bok choi',
      amount: 2,
      unit: 'heads',
      flex: 'Any cabbage, spinach, or broccoli.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochujang',
      amount: 2,
      unit: 'tbsp',
      flex: 'Start with 1 tbsp if you want it mild.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Peanut butter',
      amount: 2,
      unit: 'tbsp',
      flex: 'Smooth or crunchy. Tahini works too.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Maggi sauce',
      amount: 1,
      unit: 'tsp',
      flex: 'Or a splash more light soy.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Brown sugar, honey, or mirin.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yuzu juice',
      amount: 1,
      unit: 'tbsp',
      flex: 'Lime juice with a squeeze of lemon.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pasta water',
      amount: 0.25,
      unit: 'cup',
      flex: 'Reserved from the noodles.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Neutral oil',
      amount: 1,
      unit: 'tbsp',
      flex: 'For frying the tofu.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tbsp',
      flex: 'Toasted.',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Whisk the gochujang, peanut butter, light soy, Maggi, sesame oil, sugar, and yuzu juice together in a bowl. It will be thick and stiff at this stage, which is what you want.',
    'Cut the smoked tofu into 1 cm cubes or slabs. Fry in the neutral oil over medium-high heat for 5 to 6 minutes, turning until browned and crisp on most sides. Set aside.',
    'Bring a pot of salted water to a boil and cook the noodles according to the package.',
    'Halve the bok choi lengthwise and drop it into the noodle water for the final minute so it wilts but keeps its bite.',
    'Scoop out a mug of the starchy pasta water before draining, then drain the noodles and bok choi.',
    'Loosen the sauce with a splash of the hot pasta water, whisking until it turns glossy and pourable.',
    'Return the noodles to the warm pot, pour over the sauce, and toss until every strand is coated. Add more pasta water a spoonful at a time if it tightens up.',
    'Fold through the bok choi and tofu, then serve topped with sesame seeds.',
  ],
  notes:
    'The sauce is deliberately thick until the pasta water hits it. The starch is what makes it cling instead of sliding off. Yuzu is the ingredient doing the heavy lifting here, so add it off the heat and taste before serving. Smoked tofu needs no marinade, but plain firm tofu should be pressed and salted first.',
};
