export const kakiage = {
  name: 'Kakiage',
  param: 'kakiage',
  recipeImage: 'assets/images/kakiage.jpg',
  star: false,
  introText: 'Crispy, golden, and packed with vegetables, these fritters are the perfect snack or appetizer.',
  description:
    'These kakiage are easy to make, customizable, and delightfully crunchy. They’re great for using up leftover veggies and are a hit with both kids and adults. Pair them with your favorite dipping sauce for a perfect treat!',
  category: 'side',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrot',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Corn starch',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 2,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 0,
      unit: '',
      flex: 'for frying',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Grate or finely chop the vegetables of your choice (e.g., zucchini, cabbage, broccoli) and set them aside.',
    'Finely dice the onion, scallion, and carrot, then mix them with the grated vegetables in a large bowl.',
    'In a separate bowl, combine the flour, corn starch, baking powder, sugar, and salt. Mix well.',
    'Add the dry ingredients to the vegetable mixture and mix thoroughly.',
    'Gradually add the water, stirring until the mixture forms a thick batter. If the mixture feels too dry, add a small amount of water until it holds together.',
    'Heat a generous amount of vegetable oil in a frying pan over medium heat.',
    'Scoop spoonfuls of the batter into the hot oil, flattening them slightly with the back of the spoon.',
    'Fry the fritters for 2-3 minutes on each side, or until golden brown and crispy.',
    'Remove the fritters from the oil and place them on a plate lined with paper towels to drain excess oil.',
    'Serve immediately with your favorite dipping sauce or enjoy as is!',
  ],
  notes:
    'Feel free to experiment with different vegetables for a variety of flavors and textures. For extra flavor, add spices like paprika, cumin, or garlic powder to the batter. These fritters taste best when served hot and fresh!',
};
