export const koreanAppleCurry = {
  name: 'Korean Apple Curry',
  param: 'korean-apple-curry',
  recipeImage: 'assets/images/korean-apple-curry.jpg',
  star: false,
  introText: 'Smoked tofu, carrot, and apple in a sweet-savory galbi sauce, served over rice.',
  description:
    'A curry that leans Korean rather than Japanese: the base is galbi sauce, ketchup, and light soy instead of a roux, with grated ginger and sriracha for heat and yuzu juice to keep the sweetness in check. Apple does double duty, half of it cooked down until it dissolves into the sauce and thickens it, half added late so there are still soft chunks in the bowl. Butter-fried smoked tofu holds its texture through the simmer. About 30 minutes, most of it hands off.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: 2,
      unit: 'cups',
      flex: 'Short grain is best, but any rice works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked tofu',
      amount: 250,
      unit: 'g',
      flex: 'Firm tofu, pressed, works too.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrot',
      amount: 250,
      unit: 'g',
      flex: 'Roughly 2 large carrots.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Apple',
      amount: 2,
      unit: '',
      flex: 'A firm, tart variety. Pear works too.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 2,
      unit: 'tbsp',
      flex: 'Vegan butter or neutral oil.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: 'Season at the end, the sauce is already salty.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Galbi sauce',
      amount: 4,
      unit: 'tbsp',
      flex: 'Bulgogi marinade is a direct swap.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Grated ginger',
      amount: 1,
      unit: 'tbsp',
      flex: 'About a thumb, fresh.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yuzu juice',
      amount: 1,
      unit: 'tbsp',
      flex: 'Lemon or lime, at a push.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sriracha',
      amount: 1,
      unit: 'tbsp',
      flex: 'Start with half if you want it mild.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 200,
      unit: 'ml',
      flex: 'Stock for a deeper sauce.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 3,
      unit: '',
      flex: 'Whites into the pan, greens on top.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tbsp',
      flex: 'Toasted.',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Cook the rice in your preferred way.',
    'Cut the smoked tofu into 1.5 cm cubes. Slice the carrots into thin half moons. Core and dice the apples, keeping the two halves separate: one apple diced small, one in larger chunks. Slice the scallions, whites and greens apart.',
    'Melt the butter in a wide pan over medium-high heat. Fry the tofu for 5 to 6 minutes, turning until browned on most sides, then set aside.',
    'Drop the heat to medium and add the carrots, scallion whites, and grated ginger to the same pan. Cook for 4 to 5 minutes until the carrots start to soften and the ginger smells sweet rather than sharp.',
    'Stir in the finely diced apple, galbi sauce, light soy, ketchup, and sriracha, then pour in the water. Bring to a simmer.',
    'Simmer uncovered for 12 to 15 minutes, stirring now and then. The small apple dice will break down and thicken the sauce.',
    'Add the larger apple chunks and the tofu, and simmer for another 4 minutes so the apple softens but keeps some bite.',
    'Take the pan off the heat, stir through the yuzu juice, and season with salt to taste.',
    'Spoon over the rice and top with the scallion greens and sesame seeds.',
  ],
  notes:
    'Galbi sauces vary a lot in sweetness and salt, so taste before adding the full teaspoon of salt. The yuzu goes in off the heat, where it stays bright instead of cooking flat. If your sauce tightens too much while simmering, loosen it with a splash of water. A teaspoon of curry powder added with the ginger pushes this closer to a conventional curry if that is what you are after.',
};
