export const lemonPepperGarlicChickpeas = {
  name: 'Lemon Pepper Garlic Chickpeas',
  param: 'lemon-pepper-garlic-chickpeas',
  recipeImage: 'assets/images/lemon-pepper-garlic-chickpeas.jpg',
  star: false,
  introText: 'Creamy, garlicky chickpeas with a bright lemon pepper flavor in a rich sauce.',
  description:
    'These lemon pepper garlic chickpeas are a comforting and flavorful dish that combines the warmth of garlic, the brightness of lemon pepper, and the creaminess of a rich sauce. The nutritional yeast adds a subtle savory depth while the optional cheese makes it even more indulgent. Perfect served with crusty bread for dipping.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Butter',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon pepper spice mix',
      amount: 2,
      unit: 'tsp',
      flex: 'Make your own with lemon zest and black pepper',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 1.5,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 0.75,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas',
      amount: 230,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili powder',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Nutritional yeast',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cheese',
      amount: 50,
      unit: 'g',
      flex: 'Any melting cheese',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Chives',
      amount: 2,
      unit: 'tbsp',
      flex: 'Any fresh herbs like oregano, parsley, cilantro, or basil',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Bread',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Heat the butter in a large pan over medium heat.',
    'Add the minced garlic and lemon pepper spice mix. Sauté for 1-2 minutes until fragrant.',
    'Sprinkle in the flour and stir constantly for 1 minute to cook out the raw flour taste.',
    'Gradually add the water, whisking constantly to prevent lumps, until you have a thick sauce consistency.',
    'Add the chickpeas, cream, chili powder, MSG, sugar, salt, and nutritional yeast. Stir to combine.',
    'Simmer for 5 minutes, stirring occasionally, until the sauce has thickened and the chickpeas are heated through.',
    'If using cheese, stir it in at the end and let it melt.',
    'Taste and adjust seasoning as needed.',
    'Garnish with fresh herbs if desired and serve hot with bread.',
  ],
  notes:
    "This dish is very adaptable - you can adjust the thickness of the sauce by adding more or less water. If you don't have lemon pepper spice mix, you can make your own by combining lemon zest, black pepper, and perhaps a pinch of garlic powder. A wonderful Mexican alternative to this spice mix is Tajín, which is a chili-lime seasoning that adds a nice kick.",
};
