export const leonChimichurri = {
  name: 'León Chimichurri',
  param: 'leon-chimichurri',
  recipeImage: 'assets/images/leon-chimichurri.jpg',
  star: false,
  introText: 'A creamy and flavorful chimichurri-style sauce with a León twist.',
  description:
    "This León chimichurri is a unique take on the classic Argentinian sauce, featuring a creamy mayo base with the perfect balance of heat from red pepper flakes and depth from garlic powder and mustard. The milk helps create a smooth, pourable consistency that's perfect as a condiment or dressing.",
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Mayo',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red pepper flakes',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mustard',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a small bowl, combine the mayo, red pepper flakes, salt, garlic powder, and mustard.',
    'Whisk together until well combined.',
    'Gradually add the milk, whisking constantly, until you reach your desired consistency.',
    'Taste and adjust seasoning as needed.',
    'Let the sauce sit for 10-15 minutes to allow the flavors to meld before serving.',
    'Serve as a condiment or dressing.',
  ],
  notes:
    'This sauce can be stored in the refrigerator for up to a week. Adjust the milk quantity to achieve your preferred consistency - use less for a thicker sauce or more for a thinner dressing. The longer it sits, the more the flavors will develop.',
};
