export const mangoSerranoMuffins = {
  name: 'Mango Serrano Muffins',
  param: 'mango-serrano-muffins',
  recipeImage: 'assets/images/mango-serrano-muffins.jpg',
  star: false,
  introText:
    'These unique mango serrano muffins combine the tropical sweetness of ripe mango with a subtle kick from fresh serrano chili. Perfect for adventurous snackers or as a surprising breakfast treat!',
  description:
    'This recipe transforms classic muffins by using juicy mango instead of banana and omitting oats for a lighter crumb. The addition of serrano chili adds a gentle heat that pairs beautifully with the mango’s sweetness. These muffins are moist, flavorful, and sure to impress anyone who loves a sweet-and-spicy twist.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mango',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Serrano chili',
      amount: 1,
      unit: 'medium',
      flex: 'Any choice of chili can be used, adjust to taste.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any light-colored vinegar like rice or apple cider vinegar works well.',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line muffin tins with paper liners.',
    'Prepare the mango by peeling and mashing it. Finely mince the serrano chili.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and the white sugar.',
    'In a separate bowl, combine the mango, serrano chili, brown sugar, oil, milk, and vinegar. Whisk until well mixed.',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 18 minutes if using small muffin ramekins, 20-23 min if using large muffin ramekins, or until a toothpick inserted into the center comes out clean.',
    'Allow the muffins to cool in the tin for 20 minutes before serving.',
  ],
  notes:
    'Use very ripe mango for the best flavor and sweetness. Adjust the amount of serrano chili to your spice preference, or omit seeds for less heat. For extra flavor, consider adding a pinch of ground ginger, tajin, or lime zest. Store in an airtight container at room temperature for up to 3 days, or refrigerate for longer freshness. Can also be frozen. Sprinkle sugar on top for a sweet, crusty surface.',
};
