export const mushroomBourguignon = {
  name: 'Mushroom Bourguignon',
  param: 'mushroom-bourguignon',
  recipeImage: 'assets/images/mushroom-bourguignon.jpg',
  star: false,
  introText:
    'This hearty mushroom bourguignon is a rich and comforting dish, perfect for cozy evenings or special occasions.',
  description:
    'A vegan take on the classic French dish, mushroom bourguignon combines earthy mushrooms, sweet root vegetables, and a velvety red wine sauce for a deeply flavorful and satisfying meal. Serve it with mashed potatoes for the ultimate comfort food experience.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Potatoes',
      amount: 6,
      unit: 'medium',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrots',
      amount: 2,
      unit: 'large',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Parsnip',
      amount: 1,
      unit: 'large',
      flex: 'Or another root vegetable like celery root or turnip.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 800,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tbsp',
      flex: 'Vegetable bouillon or stock cube can be used instead.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mushrooms',
      amount: 4,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 3,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Oregano',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Balsamic vinegar',
      amount: 80,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red wine',
      amount: 0.5,
      unit: 'cup',
      flex: 'Water or vegetable broth can be used instead.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cornstarch',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Peel and chop the potatoes, carrots, and parsnip into chunks. Bring 800 ml of water to a boil in a large pot, add the salt, and boil the root vegetables for 25 minutes until tender.',
    'Drain the vegetables and mash them with the vegan butter and cream. Set aside.',
    'Meanwhile, add butter or oil in a large skillet over medium heat. Add the mushrooms and onions, cooking until softened and lightly browned, about 8–10 minutes.',
    'Add the minced garlic, oregano, and white pepper to the skillet. Stir well and cook for another 2–3 minutes until fragrant.',
    'Deglaze the skillet by adding the balsamic vinegar, light soy sauce, and red wine. Stir and let it simmer for 5 minutes to reduce slightly.',
    'In a small bowl, mix the cornstarch with 2 tablespoons of water to create a slurry. Slowly pour the slurry into the skillet while stirring to thicken the sauce.',
    'Taste the sauce and adjust the seasoning as needed. Serve the mushroom bourguignon over the mashed root vegetables.',
  ],
  notes:
    'You can also add fresh herbs like thyme or parsley for garnish. This dish pairs wonderfully with a side of crusty bread or a fresh green salad.',
};
