export const mushroomPasta = {
  name: 'Mushroom Pasta',
  param: 'mushroom-pasta',
  recipeImage: 'assets/images/mushroom-pasta.jpg',
  star: false,
  introText: 'A creamy and flavorful mushroom pasta that is quick and easy to make, perfect for a weeknight dinner.',
  description:
    'This mushroom pasta combines the earthy flavors of mushrooms with a creamy sauce, creating a comforting and satisfying dish. The addition of bouillon enhances the umami taste, while the optional chickpeas or other protein add a boost of nutrition.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Spaghetti',
      amount: 150,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1.5,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon cube',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mushrooms',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dijon mustard',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Season the mushrooms with salt, white pepper, MSG, dijon mustard, and sugar.',
    'Cook the mushrooms with seasoning in butter or oil over medium heat.',
    'Add water and bouillon cube and stir until the cube has disolved, then add the spaghetti.',
    'Cook under a lid for about 10 minutes on medium heat, checking and stirring once after 5 minutes.',
    'Add cream and cook until the pasta is done and the sauce is creamy.',
  ],
  notes: 'This mushroom pasta is best served immediately. Adjust the seasoning to taste and enjoy a comforting meal.',
};
