export const mutabbal = {
  name: 'Mutabbal',
  param: 'mutabbal',
  recipeImage: 'assets/images/mutabbal.jpg',
  star: false,
  introText:
    'Mutabbal is a creamy, smoky, and flavorful eggplant dip that makes for the perfect appetizer or side dish. It’s a classic Middle Eastern favorite that pairs well with pita bread or fresh veggies.',
  description:
    'Mutabbal is a traditional Middle Eastern dip made from roasted eggplants blended with tahini, garlic, lemon juice, and a hint of olive oil. Its rich and smoky flavor makes it a crowd-pleaser and a versatile addition to any table. Enjoy it as a dip, spread, or even as part of a mezze platter.',
  category: 'side',
  tags: {
    quick: false,
    easy: true,
    temperature: '225',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Eggplant',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tahini',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 1,
      unit: 'clove',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 0.5,
      unit: 'lemon',
      flex: 'Lime',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pomegranate',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Sumac',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Mint',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Olive oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Preheat your oven to 450°F (225°C).',
    'Pierce the eggplant a few times with a fork and place it on a baking tray. Roast in the oven for 50 minutes, until the skin is charred and the flesh is soft.',
    'Once cooled, peel off the eggplant’s skin and chop up the flesh with a knife or a food processor.',
    'Add the tahini, garlic, lemon juice, cumin, and salt to a bowl together with the eggplant and mix.',
    'Taste and adjust seasoning as needed, adding more salt or lemon juice to suit your preference.',
    'Transfer to a serving bowl, drizzle with a bit of olive oil, and garnish with fresh herbs or a sprinkle of paprika, if desired.',
    'Serve with warm pita bread or fresh vegetables for dipping.',
  ],
  notes:
    'For an extra smoky flavor, you can grill the eggplants instead of roasting them in the oven. Mutabbal tastes even better after resting for a few hours in the fridge, allowing the flavors to meld together.',
};
