export const oatMuffins = {
  name: 'Oat Muffins',
  param: 'oat-muffins',
  recipeImage: 'assets/images/oat-muffins.jpg',
  star: false,
  introText:
    'These moist and hearty oat muffins are a delicious twist on a classic sponge cake. Perfect for a wholesome breakfast or snack!',
  description:
    'This recipe adapts the light and airy sponge cake into wholesome oat muffins. The addition of oats provides a satisfying texture and added fiber, making them a perfect grab-and-go treat. They remain moist and flavorful with the combination of dairy-free milk, yogurt, and oil, without the need for eggs.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rolled Oats',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yogurt',
      amount: 50,
      unit: 'g',
      flex: 'Milk, buttermilk, or a puréed fruit like banana or applesauce.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any light-colored vinegar like rice or apple cider vinegar works well.',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, oats, baking powder, baking soda, salt, and the white sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the yogurt, brown sugar, oil, and milk. Whisk until smooth (but no worries if there are some brown sugar lumps, just leave them be).',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 18 minutes if using small muffin ramekins, 20-23 min if using large muffin ramekins, or until a toothpick inserted into the center comes out clean.',
    'Allow the muffins to cool in the tin for 20 minutes before serving.',
  ],
  notes:
    'For oat muffins, standard muffin tins are ideal. For added flavor, consider incorporating vanilla extract, cinnamon (1/2 to 1 tsp), or even a handful of dried fruit (like raisins or cranberries) into the batter. Store in an airtight container or bag at room temperature for up to 3 days, or refrigerate for longer freshness. Can also be frozen. Sprinkle sugar on top for a sweet, crusty surface. If mixing in berries like blueberries or strawberries, add up to 100g. This replaces the 50g of yogurt. Or if making banana or apple sauce muffins, replace the yogurt at a 1:1 ratio',
};
