export const quinoaSalad = {
  name: 'Quinoa Salad',
  param: 'quinoa-salad',
  recipeImage: 'assets/images/quinoa-salad.jpg',
  star: false,
  introText:
    'A fresh and filling quinoa salad that combines roasted chickpeas, cauliflower, and vibrant veggies for a nutrient-packed, flavorful dish.',
  description:
    'This hearty quinoa salad is the perfect blend of roasted chickpeas, cauliflower, and colorful vegetables. The smoky flavor of paprika paired with the sweetness of agave syrup makes the roasted components stand out, while fresh ingredients like cucumber, avocado, and tomatoes add a refreshing crunch. Preserved lemon and jalapeños give it a zesty kick, making this salad a perfect lunch or side dish.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: '200',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Chickpeas',
      amount: 400,
      unit: 'g',
      flex: 'Can replace with any beans',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cauliflower',
      amount: 1,
      unit: 'small head',
      flex: 'Broccoli or roasted carrots work as alternatives',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked paprika',
      amount: 1,
      unit: 'tsp',
      flex: 'Or whatever flavor you prefer',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Agave syrup',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any sweetener like maple syrup or sugar can be used',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Olive oil',
      amount: 2,
      unit: 'tbsp',
      flex: 'Use any neutral oil',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cucumber',
      amount: 0.5,
      unit: 'whole',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Avocado',
      amount: 1,
      unit: 'whole',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sun-dried tomatoes',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cherry tomatoes',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Jalapeños',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Roasted shallots',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Preserved lemon',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Quinoa',
      amount: 1,
      unit: 'cup',
      flex: 'Couscous, rice, or bulgur are good substitutes',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt or vegetable bouillon',
      amount: 0.5,
      unit: 'tsp or 1 cube',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bell pepper',
      amount: 1,
      unit: 'whole',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Corn',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat your oven to 200°C (392°F).',
    'Toss the chickpeas and cauliflower in a mix of smoked paprika, agave syrup, salt, and olive oil. Spread on a baking tray and roast for 40 minutes, or until golden and crispy, stirring halfway through.',
    'While the chickpeas and cauliflower roast, rinse the quinoa under cold water. Add it to a pot with 2 cups of water and 0.5 tsp salt (or a vegetable bouillon cube). Bring to a boil, then reduce heat to medium and simmer without a lid until the water has evaporated, about 15 minutes. Fluff the quinoa with a fork and set aside to cool.',
    'Chop the cucumber, avocado, cherry tomatoes, and bell pepper into bite-sized pieces. Slice the sun-dried tomatoes and jalapeños. Combine these with the roasted shallots, preserved lemon, and corn in a large mixing bowl.',
    'Once the chickpeas and cauliflower are done roasting, allow them to cool slightly, then add them to the salad.',
    'Finally, mix in the cooked quinoa. Toss everything gently to combine and adjust the seasoning with more salt or olive oil if needed.',
    'Serve the quinoa salad immediately or refrigerate for up to 3 days. Enjoy cold or at room temperature.',
  ],
  notes:
    'This quinoa salad is incredibly customizable. Feel free to experiment with different roasted veggies or spices. For a protein boost, add more chickpeas or some tempeh. The preserved lemon and jalapeños bring a unique tang and heat, but you can adjust both to your taste.',
};
