export const salsa = {
  name: 'Salsa',
  param: 'salsa',
  recipeImage: 'assets/images/salsa.jpg',
  star: false,
  introText:
    'This fresh and zesty salsa is perfect for dipping, topping tacos, or adding a burst of flavor to any dish.',
  description:
    'This classic salsa recipe combines ripe tomatoes, fresh cilantro, and a hint of lime for a bright, refreshing dip that’s easy to make and perfect for any occasion. Adjust the heat level by adding more or less jalapeño to suit your taste.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Tomato',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Shallot',
      amount: 1,
      unit: '',
      flex: 'Any onion of your choice.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Jalapeño',
      amount: 1,
      unit: '',
      flex: 'Another kind of pepper, chili flakes, or hot sauce.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime juice',
      amount: 2,
      unit: 'tbsp',
      flex: 'Another citrus or half the amount of vinegar.',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Fry the tomato, shallot, jalapeño, and garlic in a pan with some oil until slightly charred.',
    'In a food processor, blender, or mortar, combine the tomato, cilantro, shallot, jalapeño, garlic, salt, and lime juice.',
    'Pulse or mash the mixture until it reaches your desired consistency, whether chunky or smooth.',
    'Taste and adjust seasoning, adding more salt or lime juice if needed.',
    'Serve immediately or refrigerate in an airtight container for up to 3 days.',
  ],
  notes:
    'For a milder salsa, remove the seeds and membrane from the jalapeño before blending. Feel free to adjust the cilantro and lime juice to taste. This salsa pairs well with tortilla chips, tacos, or as a topping for your favorite dishes.',
};
