export const scallionPancakes = {
  name: 'Scallion Pancakes',
  param: 'scallion-pancakes',
  recipeImage: 'assets/images/scallion-pancakes.jpg',
  star: false,
  introText: 'Crispy, flaky, and loaded with fresh scallions.',
  description:
    'Scallion pancakes, or "Cong You Bing," are a beloved Chinese street food. With their flaky layers and rich scallion flavor, they’re easier to make than you might think! This recipe uses simple ingredients and requires no special equipment. Perfect as a side dish or snack, these pancakes are crispy on the outside and chewy on the inside.',
  category: 'side',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Hot water',
      amount: 1,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: '',
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a large bowl, combine the flour and salt. Gradually add the hot water while stirring with a spoon or chopsticks until a rough dough forms.',
    'Knead the dough on a floured surface for about 8-10 minutes until smooth and elastic. Cover with a damp towel and let it rest for 30 minutes.',
    'Divide the dough into four equal portions. Roll out one portion into a thin circle, about 8 inches in diameter.',
    'Sprinkle generously with sliced scallions. Roll the circle into a tight log, then coil the log into a spiral. Flatten the spiral gently with your palm, then roll it out again into a thin circle.',
    'Repeat the process with the remaining dough portions.',
    'Heat a skillet over medium heat and add a thin layer of neutral oil. Fry each pancake for 2-3 minutes on each side, or until golden brown and crispy. Add more oil as needed for each pancake.',
    'Transfer to a plate lined with paper towels to remove excess oil.',
  ],
  notes:
    'For an extra flaky texture, you can repeat the rolling and coiling process twice before frying. Serve with soy sauce, rice vinegar, or a mix of soy sauce, chili oil, and a touch of sugar for a delicious dipping sauce.',
};
