export const shakshuka = {
  name: 'Shakshuka',
  param: 'shakshuka',
  recipeImage: 'assets/images/shakshuka.jpg',
  star: false,
  introText: 'A hearty and flavorful dish with a spicy tomato sauce, perfect for breakfast or brunch.',
  description:
    'Shakshuka is a North African and Middle Eastern dish. It’s a one-pan meal that’s easy to make and packed with flavor. The sauce is made with tomatoes, bell peppers, onions, and spices, creating a rich and savory base for the eggs. Serve it with crusty bread for dipping.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Tomatoes',
      amount: 400,
      unit: 'g',
      flex: 'Canned whole, fresh, crushed, or puréed.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bell pepper',
      amount: 1,
      unit: '',
      flex: 'Any color. Can also use another vegetable like zucchini or eggplant.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: 'Any type.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 2,
      unit: 'cube',
      flex: '1 tsp salt',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 2,
      unit: 'tsp',
      flex: 'Any sweetener works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas',
      amount: 1,
      unit: 'cup',
      flex: 'Any beans or lentils work.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 1,
      unit: 'tsp',
      flex: 'Any pepper works.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Bread',
      amount: 1,
      unit: '',
      flex: 'Any bread for dipping, like pita or crusty rolls, or serve with rice, bulgur, or couscous.',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a large skillet, melt the butter over medium-high heat.',
    'Add the chopped onion and bell pepper, cooking until softened, about 5-7 minutes.',
    'Stir in the sliced or minced garlic and cook for another minute until fragrant.',
    'Stir in the vegetable bouillon, sugar, cumin, and black pepper.',
    'Add the tomatoes (if using whole, crush them with a spoon) and bring to a simmer. Cook for about 5 minutes until the sauce thickens slightly.',
    'If using chickpeas, add them now and stir to combine. Cook for another 2-3 minutes.',
    'Top the sauce with cilantro and serve with bread for dipping.',
  ],
  notes:
    'Shakshuka is a versatile dish. You can add other vegetables or proteins like (plant-based) feta cheese or sausage. Adjust the spices to your taste. It’s great for breakfast, lunch, or dinner and can be made ahead of time and reheated.',
};
