export const baklavaMuffins = {
  name: 'Baklava Muffins',
  param: 'baklava-muffins',
  recipeImage: 'assets/images/baklava-muffins.jpg',
  star: false,
  introText:
    'Fragrant muffins inspired by baklava, with ground pistachios, rose water, and a sweet, crunchy pistachio-sugar topping.',
  description:
    'These baklava muffins bring the flavors of the classic Middle Eastern pastry into a soft, fluffy muffin. Ground pistachios are folded into the batter alongside a splash of rose water, and more pistachios and sugar are sprinkled on top before baking for a beautifully crunchy crust.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '225',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rose water',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ground pistachios',
      amount: 40,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ground pistachios',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 225°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, ground pistachios, baking powder, baking soda, salt, and the sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the oil, milk, and rose water.',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Sprinkle the tops with ground pistachios and sugar.',
    'Bake for 7 minutes, then decrease the temperature to 175°C and bake for an additional 19 minutes (26 minutes total).',
    'Allow the muffins to cool for 20 minutes before serving.',
  ],
};
