export const balsamicDressing = {
  name: 'Balsamic Dressing',
  param: 'balsamic-dressing',
  recipeImage: 'assets/images/balsamic-dressing.jpg',
  star: false,
  introText: 'A balanced blend of tangy, sweet, and savory flavors, fitting any salad or roasted vegetable dish.',
  description:
    'A rich and flavorful balsamic dressing combining the sharpness of balsamic vinegar and the creamy sweetness of balsamic crème with a hint of garlic and mustard. This dressing adds a perfect balance of sweetness and acidity to salads or grilled vegetables.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Olive oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Balsamic crème',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Balsamic vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sweet mustard',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Mince the garlic finely or use a garlic press to ensure a smooth texture.',
    'In a small bowl, whisk together the olive oil, balsamic vinegar, balsamic crème, sweet mustard, and minced garlic.',
    'Add the salt and continue to whisk until the dressing is well combined and emulsified.',
    'Taste and adjust the seasoning as needed, adding more salt or mustard for flavor balance.',
    'Use immediately on your favorite salad, or store in an airtight container in the fridge for up to a week. Shake or whisk before using as the ingredients may separate over time.',
  ],
  notes:
    'For a smoother texture, you can blend the dressing with an immersion blender to further emulsify the ingredients.',
};
