export const bananaBread = {
  name: 'Banana Bread',
  param: 'banana-bread',
  recipeImage: 'assets/images/banana-bread.jpg',
  star: false,
  introText: 'Perfect for any occasion, and a great picnic food. An ideal way to use up browned, mushy bananas.',
  description:
    'The ripe bananas add natural sweetness and moisture, while the combination of white and brown sugar gives it a rich flavor. It’s perfect for breakfast, a snack, or even dessert. Bring out the loaf dish for this one.',
  category: ['dessert', 'breakfast', 'snack'],
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Flour',
      amount: 140,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.125,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ripe bananas',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line a loaf dish with parchment paper.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and white sugar.',
    'In a separate bowl, mash the ripe bananas and combine with the oil, brown sugar, and milk. Whisk until smooth.',
    'Add the wet and dry ingredients together, stirring until just combined.',
    'Pour the batter into a loaf dish.',
    'Bake for 45 minutes, or until a toothpick inserted into the center comes out clean.',
    'Allow the cake to cool for at least another 30 minutes before cutting into it.',
  ],
  notes:
    'Whisk the dry ingredients with a balloon whisk to minimize risk for flour lumps. This spongy bread/cake can also be used as a base for layered cakes or cupcakes. Store in an airtight container or bag at room temperature for up to 3 days. Can also be frozen.',
};
