export const bananaMuffins = {
  name: 'Banana Muffins',
  param: 'banana-muffins',
  recipeImage: 'assets/images/banana-muffins.jpg',
  star: false,
  introText:
    'These moist and flavorful banana muffins are a delicious way to use up ripe bananas. Simple, sweet, and perfect for breakfast or a snack!',
  description:
    'Classic banana muffins made with smooched bananas for natural sweetness and moisture. These muffins have a tender crumb and rich banana flavor that makes them irresistible.',
  category: ['dessert', 'breakfast', 'snack'],
  tags: {
    quick: true,
    easy: true,
    temperature: '225',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 120,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Banana',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 225°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and the sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the oil and smashed banana.',
    'Add the dry ingredients to the wet ingredients, stirring until combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 7 minutes, then decrease the temperature to 175°C and bake for an additional 19 minutes (26 minutes total).',
    'Allow the muffins to cool for 20 minutes before serving.',
  ],
  notes:
    '1 large peeled Cavendish banana is about 200 grams. Use very ripe bananas for best flavor. Store in an airtight container at room temperature for up to 3 days, or refrigerate for longer freshness. These muffins freeze well. For extra flavor, you can add chocolate chips, nuts, or a sprinkle of cinnamon to the batter. Use salt according to your own taste, somewhere between 1/4 and 1/2 teaspoon.',
};
