export const bananaOatMuffins = {
  name: 'Banana Oat Muffins',
  param: 'banana-oat-muffins',
  recipeImage: 'assets/images/banana-oat-muffins.jpg',
  star: false,
  introText:
    'These moist and hearty banana oat muffins combine the wholesome goodness of oats with the natural sweetness of ripe bananas. Perfect for a nutritious breakfast or snack!',
  description:
    'This recipe add oats to the standard muffin recipe, incorporating more fiber and nutrition, making it a sweet breakfast or snack consideration.',
  category: ['dessert', 'breakfast', 'snack'],
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rolled Oats',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ripe banana',
      amount: 1,
      unit: 'medium',
      flex: 'About 50g when mashed - use very ripe bananas for best flavor',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any light-colored vinegar like rice or apple cider vinegar works well.',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line muffin tins with paper liners.',
    'Mash the ripe banana in a small bowl until smooth with only small lumps remaining.',
    'In a large mixing bowl, whisk together the flour, oats, baking powder, baking soda, salt, and the white sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the mashed banana, brown sugar, oil, milk, and vinegar. Whisk until smooth (but no worries if there are some brown sugar lumps, just leave them be).',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 18 minutes if using small muffin ramekins, 20-23 min if using large muffin ramekins, or until a toothpick inserted into the center comes out clean.',
    'Allow the muffins to cool in the tin for 20 minutes before serving.',
  ],
  notes:
    'For banana oat muffins, standard muffin tins are ideal. The riper the banana, the sweeter and more flavorful your muffins will be - brown spotted bananas work perfectly! For added flavor, consider incorporating vanilla extract, cinnamon (1/2 to 1 tsp), or even a handful of chopped walnuts or chocolate chips into the batter. Store in an airtight container or bag at room temperature for up to 3 days, or refrigerate for longer freshness. Can also be frozen. Sprinkle sugar on top for a sweet, crusty surface. If you want to add berries like blueberries, use about 50g and fold them in at the end.',
};
