export const bulgurSalad = {
  name: 'Kısır',
  param: 'bulgur-salad',
  recipeImage: 'assets/images/bulgur-salad.jpg',
  star: false,
  introText: 'Known in Turkey as Kısır, a bulgur salad packed with fresh vegetables, herbs, and sour notes.',
  description:
    'Bulgur sala or Kısır is a versatile dish that combines the nutty flavor of bulgur wheat with a medley of fresh vegetables, herbs, and a zesty dressing. It’s quick to prepare, wholesome, and can be enjoyed cold, making it ideal for meal prep or picnics.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Fine bulgur',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pickles',
      amount: 0.5,
      unit: 'cup',
      flex: 'Cucumber.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 0.5,
      unit: 'cup',
      flex: 'Sundried tomato.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato purée',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 0.5,
      unit: 'cup',
      flex: 'Any herb you like, such as dill, mint, or parsley. Or all of them together!',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas',
      amount: 0.5,
      unit: 'cup',
      flex: 'Any bean you like, such as black beans or kidney beans.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sumac',
      amount: 1,
      unit: 'tbsp',
      flex: 'Citrus juice, like lemon or lime.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 1,
      unit: 'tsp',
      flex: 'Any chili sauce.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pomegranate molasses',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Bring the water to a simmer with the bouillon cube until the cube is dissolved.',
    'In a bowl, add the bulgur, bouillon, and tomato purée and mix it thoroughly.',
    'Add spices along with the olive oil and mix again.',
    'Dice up all the vegetables and herbs, then add the pickles, tomatoes, herbs, beans, and green onions to the bulgur mix.',
    'Add the cooked and cooled bulgur to the bowl of vegetables and pour the dressing over the top. Toss everything together until well combined.',
    'Taste and adjust seasoning if necessary. Serve immediately or refrigerate for an hour to allow the flavors to meld.',
  ],
  notes:
    'This bulgur salad can be customized with any of your favorite vegetables or herbs. It also keeps well in the fridge for up to 3 days, making it a great option for meal prep. Try eating it with lettuce wraps or cups as bulgur vehicles.',
};
