export const carrotMuffins = {
  name: 'Carrot Muffins',
  param: 'carrot-muffins',
  recipeImage: 'assets/images/carrot-muffins.jpg',
  star: false,
  introText:
    'Warmly spiced carrot muffins with cinnamon, cardamom, and nutmeg — moist, fragrant, and perfect for autumn.',
  description:
    'These carrot muffins are soft and tender, made with finely grated carrot for moisture and a warm blend of cinnamon, cardamom, and nutmeg for cozy, aromatic flavor. A simple twist on the classic muffin that feels like a treat any time of day.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '225',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 120,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cardamom',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Nutmeg',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrot, finely grated and squeezed',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 225°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, sugar, cinnamon, cardamom, and nutmeg. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the oil and milk.',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Fold in the grated and squeezed carrot until evenly distributed.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 7 minutes, then decrease the temperature to 175°C and bake for an additional 19 minutes (26 minutes total).',
    'Allow the muffins to cool for 20 minutes before serving.',
  ],
};
