export const cornChowder = {
  name: 'Mapo Tofu',
  param: 'mapo-tofu',
  recipeImage: 'assets/images/mapo-tofu.jpg',
  star: true,
  introText: 'A classic Szechuan dish featuring silky tofu in a spicy, savory sauce.',
  description:
    'Mapo Tofu is a beloved Szechuan recipe characterized by its bold flavors from doubanjiang, garlic, ginger, and Szechuan oil. This dish combines soft tofu with soy mince and is finished with a touch of cornstarch slurry for a silky sauce. Perfect served over steamed rice.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Tofu',
      amount: 400,
      unit: 'g',
      flex: 'Any firmness of tofu',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy mince',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Doubanjiang',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Szechuan oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 1,
      unit: 'cube',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cornstarch slurry',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Heat oil in a pan over medium-high heat. Add minced garlic, ginger, and half of the scallions. Sauté until fragrant.',
    'Add the ground pork and cook until browned.',
    'Stir in the doubanjiang and soy sauce; cook for another minute.',
    'Pour in the chicken broth and bring to a simmer.',
    'Gently add the tofu cubes and simmer for 5–7 minutes, allowing the flavors to meld.',
    'Stir in the chili oil and sprinkle in the ground Szechuan peppercorns.',
    'Add the cornstarch slurry to thicken the sauce, stirring carefully to avoid breaking the tofu.',
    'Garnish with the reserved scallions and serve hot over steamed rice.',
  ],
  notes: 'Soy mince is not necessary and can be omitted',
};
