export const gamjaJorim = {
  name: 'Gamja Jorim',
  param: 'gamja-jorim',
  recipeImage: 'assets/images/gamja-jorim.jpg',
  star: false,
  introText:
    'Gamja Jorim, or braised potatoes, is a beloved Korean side dish featuring tender potatoes in a savory-sweet soy glaze.',
  description:
    'This dish is all about timing to achieve the perfect texture—tender on the inside and slightly crisp on the outside. This recipe uses Potatoes and infuses them with flavors of garlic, soy sauce, and sesame, creating an irresistible savory glaze.',
  category: 'side',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Potato',
      amount: 4,
      unit: 'medium',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Oil',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red onion',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bell pepper',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili',
      amount: 2,
      unit: '',
      flex: 'Any chili or chili flakes.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown rice syrup',
      amount: 2,
      unit: 'tbsp',
      flex: 'Any syrup.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy sauce',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a large skillet, heat the oil over high heat. Add the potatoes and cook for 4 to 5 minutes until they begin to brown.',
    'Add the onion, garlic, bell pepper, and chilies. Sauté for another 2 minutes, then add the brown rice syrup and toss to coat the vegetables evenly.',
    'Deglaze the pan with the soy sauce, then add the vegetable broth and bring the mixture to a boil. Reduce the heat, cover, and cook for 15 minutes, until the potatoes are almost fork-tender.',
    'Once the potatoes are nearly fork-tender, remove the lid and continue cooking for an additional 2 minutes, allowing the braising liquid to reduce to a glaze-like consistency.',
    'Add the sesame oil, black pepper, and sesame seeds. Do not stir too much once the potatoes are fully cooked. Serve warm.',
  ],
  notes:
    'For best results, use waxy potatoes like Yukon Gold rather than starchy varieties like russets. Avoid stirring too often after the potatoes are tender, as it may break them up. This dish is perfect as a side to rice or other Korean dishes.',
};
