// export const karēRaisu = {
export const karēRaisu = {
  name: 'Karē Raisu',
  param: 'kare-raisu',
  recipeImage: 'assets/images/kare-raisu.jpg',
  star: false,
  introText:
    'Karē raisu, or Japanese curry rice, is a staple in Japanese households and is loved for its simplicity and deliciousness.',
  description:
    'Karē raisu is a beloved Japanese comfort food that features a thick, savory curry sauce made with a variety of vegetables and protein, served over steamed rice. The curry is typically mildly spiced, making it suitable for all ages. It’s a versatile dish that can be customized with different ingredients based on personal preferences.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: 2,
      unit: 'cups',
      flex: 'Any rice.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Potato',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrot',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Parsnip',
      amount: 250,
      unit: 'g',
      flex: 'Any root vegetable.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 2,
      unit: '',
      flex: 'Any onion.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red lentils',
      amount: 1,
      unit: 'cup',
      flex: 'Faux meat or beans.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1200,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Karē bouillion',
      amount: 3,
      unit: 'cubes',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark soy',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cook the rice in your preferred way.',
    'In a big pot, add the chopped onion and root vegetables. Add the water and bring to a boil.',
    'After boiling for 10 minutes on medium-high heat, add the lentils and karē cubes. Stir and let it boil for another 10-15 minutes or until the vegetables are tender. If you want a thicker sauce, let it simmer for a few more minutes.',
  ],
  notes:
    'Feel free to adjust the sweetness or add more spices like nutmeg, cocoa powder, or cardamom for extra flavor. You can also experiment with adding a spoonful of peanut butter for added nutty richness.',
};
