export const kladdkaka = {
  name: 'Kladdkaka',
  param: 'kladdkaka',
  recipeImage: 'assets/images/kladdkaka.jpg',
  star: false,
  introText:
    'Kladdkaka is a rich and gooey Swedish chocolate cake, similar to a brownie but with a delightfully underbaked center.',
  description:
    'Kladdkaka is the Swedish answer to a gooey chocolate cake. This simple, indulgent dessert is known for its sticky, almost fudge-like center. The caramelized syrup and sugar bring out the deep, rich chocolate flavor, and the addition of dark chocolate adds an extra layer of richness.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '150',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Butter',
      amount: 150,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Syrup',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 0.75,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'All-purpose flour',
      amount: 0.75,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cocoa powder',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark chocolate (>80%)',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a medium saucepan, melt the vegan butter over medium heat. Add the plant-based milk, syrup, and sugar (and optional dark chocolate) in the pan when adding the butter. Alternatively melt the butter in a microwave.',
    'Remove the pot from heat and stir in the dark chocolate (if using) until fully melted.',
    'Add the flour, cocoa powder, and salt to a bowl, then pour in the wet ingredients. Mix until you get a smooth batter.',
    'Grease a 9x9 inch baking dish and pour the batter into it, spreading it evenly.',
    'Bake at 150°C for about 24 minutes (16 minutes if using oven fan setting). The cake should be soft and gooey in the center.',
    'Let the cake cool slightly before serving, as it will set a bit more as it cools. Sift powdered sugar on top. Serve warm with vegan whipped cream or a scoop of plant-based ice cream if desired.',
  ],
  notes:
    'Kladdkaka is traditionally very soft and slightly underbaked, giving it its signature gooey texture. For a firmer texture, you can bake it for a few more minutes, but be careful not to overbake it. You can also sprinkle some powdered sugar on top for extra sweetness or serve it with fresh berries.',
};
