export const mayonnaise = {
  name: 'Mayonnaise',
  param: 'mayonnaise',
  recipeImage: 'assets/images/mayonnaise.jpg',
  star: false,
  introText:
    'A rich and creamy mayonnaise that is perfect as a dip or spread. This plant-based version uses aquafaba to create a luscious texture similar to traditional mayo, but without eggs.',
  description:
    'This Mayonnaise is a versatile and flavorful condiment, made creamy by using aquafaba (chickpea water) as an egg substitute. With a punch of garlic and a hint of tangy lemon, this mayo is perfect for sandwiches, dipping, or drizzling over roasted vegetables. The black salt adds an eggy flavor, making it a great vegan alternative to traditional mayo.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Aquafaba',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Canned chickpeas',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dijon mustard',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black salt',
      amount: 1,
      unit: 'tsp',
      flex: 'Any salt works',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Simmer the aquafaba in a small pot over medium heat for about 3 minutes, then remove from heat and let it cool slightly.',
    'Add the cooled aquafaba, lemon juice, canned chickpeas, Dijon mustard, garlic, and black salt to a blender.',
    'Begin blending the mixture at a low speed (about 30% blender speed) to avoid overheating the ingredients.',
    'While blending, slowly drizzle in the vegetable oil in a steady stream, allowing the mayo to emulsify and thicken.',
    'If the mayo is too thin, drizzle in a little more oil until you reach your desired consistency. Be careful not to overheat the mixture as it can cause the mayo to split.',
    'Taste and adjust seasoning if needed. You can add more lemon juice or salt to taste.',
    'Use immediately or store in an airtight container in the fridge for up to a week.',
  ],
  notes:
    'Make sure to keep the blender at a low speed while adding the oil to prevent the mayo from splitting. You can also experiment with different oils, such as olive oil for a more robust flavor. Black salt (kala namak) gives this mayo an "eggy" flavor, but regular salt can be used if you prefer.',
};
