export const muffins = {
  name: 'Muffins',
  param: 'muffins',
  recipeImage: 'assets/images/muffins.jpg',
  star: false,
  introText:
    'These moist and hearty classic muffins are a delicious twist on a classic sponge cake. Perfect for a wholesome breakfast or snack!',
  description:
    'Classic muffins are soft, fluffy, and lightly sweetened individual cakes, perfect for breakfast or a snack. They have a tender crumb and a golden top, and can be enjoyed plain or with a variety of mix-ins like fruit, chocolate chips, or nuts. Easy to make and endlessly versatile, muffins are a staple in home baking.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '225',
    clean: true,
    cheap: true,
  },
  versions: [
    {
      name: 'Oat Muffins',
      param: 'oat-muffins',
    },
    {
      name: 'Banana Muffins',
      param: 'banana-muffins',
    },
    {
      name: 'Banana Oat Muffins',
      param: 'banana-oat-muffins',
    },
    {
      name: 'Mango Serrano Muffins',
      param: 'mango-serrano-muffins',
    },
    {
      name: 'Basil Strawberry Muffins',
      param: 'basil-strawberry-muffins',
    },
    {
      name: 'Chocolate Muffins',
      param: 'chocolate-muffins',
    },
    {
      name: 'Blueberry Yuzu Muffins',
      param: 'blueberry-yuzu-muffins',
    },
    {
      name: 'Baklava Muffins',
      param: 'baklava-muffins',
    },
    {
      name: 'Carrot Muffins',
      param: 'carrot-muffins',
    },
  ],
  ingredients: [
    {
      name: 'Flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 120,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flavored syrup',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Fruit',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 225°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and the sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the oil, milk, and flavored syrup.',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 7 minutes, then decrease the temperature to 175°C and bake for an additional 19 minutes (26 minutes total).',
    'Allow the muffins to cool for 20 minutes before serving.',
  ],
  notes:
    'We can also bake it in 175°C for the whole bake, but then the time should be increased to 28 minutes (if using large muffin liners). Bake for 22 minutes total instead if using small muffin ramekins. Store in an airtight container or bag at room temperature for up to 3 days, or refrigerate for longer freshness. Can also be frozen and reheated in the microwave. Sprinkle sugar on top for a sweet, crusty surface. If mixing in berries like blueberries or strawberries, only add up to 100g. If adding frozen fruit, do not thaw before mixing in. If mashing the fruit like banana or using a jam, use 200g and replace all the milk with it. If doing a streusel, add together 0.25 cups of flour, 0.25 cups of brown sugar, 3 tbsp of butter, 0.25 cups of walnuts, and 0.25 tsp of salt - then sprinkle on top before baking.',
};
