export const mushroomPolenta = {
  name: 'Mushroom Polenta',
  param: 'mushroom-polenta',
  recipeImage: 'assets/images/mushroom-polenta.jpg',
  star: false,
  introText:
    'A warm and hearty dish perfect for any occasion. This creamy polenta is topped with a savory mixture of mushrooms and onions, enhanced by the umami flavors of balsamic vinegar and soy sauce.',
  description:
    'Polenta with mushrooms and onions is a simple yet elegant dish that balances the creamy texture of polenta with the deep, rich flavors of sautéed mushrooms and onions. The addition of balsamic vinegar and soy sauce creates a perfect umami-packed topping, making it a comforting and satisfying meal.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Polenta',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 4,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bouillon',
      amount: 2,
      unit: 'tbsp',
      flex: '2 teaspoons salt.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mushroom',
      amount: 3,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Balsamic vinegar',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy sauce',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 50,
      unit: 'g',
      flex: 'Any oil.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Thyme',
      amount: 0.25,
      unit: 'cup',
      flex: 'Any herb like rosemary, oregano, basil, parsley, etc.',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a medium pot, bring the water or vegetable broth to a boil. Slowly whisk in the polenta, reducing the heat to low. Cook while stirring frequently until thick and creamy, about 20 minutes. Season with salt and pepper as desired.',
    'While the polenta cooks, heat 2 tablespoons of olive oil in a large skillet over medium heat. Add the chopped onion and cook until softened, about 5 minutes.',
    'Add the minced garlic and sliced mushrooms to the skillet. Sauté until the mushrooms release their moisture and begin to brown, about 7–10 minutes.',
    'Stir in the balsamic vinegar and soy sauce, cooking for an additional 2–3 minutes to allow the flavors to meld. Remove from heat.',
    'Spoon the creamy polenta onto serving plates or bowls, and top with the mushroom and onion mixture.',
    'Garnish with fresh parsley and serve immediately.',
  ],
  notes:
    'For a richer polenta, substitute half the water or broth with plant-based milk. You can also add nutritional yeast for a cheesy flavor. Feel free to experiment with different mushroom varieties for added depth of flavor.',
};
