export const orangeTofu = {
  name: 'Orange Tofu Donburi',
  param: 'orange-tofu',
  recipeImage: 'assets/images/orange-tofu.jpg',
  star: true,
  introText: 'A flavorful and tangy orange tofu donburi that is perfect for a quick and satisfying meal.',
  description:
    'This orange tofu donburi combines the sweetness of orange with the savory flavors of light soy and garlic. The tofu is cooked until crispy, before being tossed in a delicious orange sauce. Serve it over rice for a complete meal.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: null,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tofu',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic cloves',
      amount: 4,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 0.25,
      unit: 'cup',
      flex: 'Any sugar or sweetener can be used',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Gochugaru',
      amount: 2,
      unit: 'tsp',
      flex: 'Any chili flakes / chili / hot sauce can be used',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rice vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any vinegar can be used',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Orange juice',
      amount: 0.5,
      unit: 'cup',
      flex: 'One large orange',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cornstarch',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Spring onion',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Cook your rice.',
    'Cut the tofu into cubes.',
    'In a pan on medium-high heat, heat some vegetable oil and cook the tofu until crispy. Set aside.',
    'In the same pan, lower to medium heat and add the garlic, light soy sauce, brown sugar, MSG, gochugaru, and rice vinegar. Stir to combine.',
    'Add the orange juice and a cornstarch slurry made from 1 part starch and two parts water. Cook until the sauce thickens a bit.',
    'Add the tofu back to the pan and toss to coat in the sauce.',
    'Serve the orange tofu over rice and garnish with chopped spring onions and sesame seeds.',
  ],
  notes: 'Try this dunburi with sushi rice. Toss the tofu in the sauce just before serving to keep it crispy.',
};
