export const peanutButterCornflakeBars = {
  name: 'Peanut Butter Cornflake Bars',
  param: 'peanut-butter-cornflake-bars',
  recipeImage: 'assets/images/peanut-butter-cornflake-bars.jpg',
  star: false,
  introText: 'These Peanut Butter Cornflake Bars are the perfect no-bake treat – crunchy, nutty, and satisfying.',
  description:
    'Indulge in the crunchy and nutty delight of these Peanut Butter Cornflake Bars. Combining the wholesome flavors of peanut butter, tahini, and a touch of maple syrup, these bars are bound together with cornflakes, cashews, and sesame seeds. They’re topped with a decadent layer of dark chocolate, making them an irresistible treat that’s both vegan and refined sugar-free.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Cornflakes',
      amount: 3,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cashews',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Peanut butter',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tahini',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Maple syrup',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan butter',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vanilla aroma',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark chocolate',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Line a square baking dish with parchment paper and set aside.',
    'In a large mixing bowl, combine the cornflakes, cashews, and sesame seeds. Mix well.',
    'In a small saucepan over low heat, combine the peanut butter, tahini, maple syrup, and vegan butter. Stir until smooth and fully melted.',
    'Remove the saucepan from heat and stir in the vanilla aroma (if using) and salt.',
    'Pour the peanut butter mixture over the cornflake mixture and stir gently to coat everything evenly.',
    'Transfer the mixture to the prepared baking dish. Press it firmly into an even layer using the back of a spoon or a spatula.',
    'Melt the dark chocolate in a heatproof bowl over a pot of simmering water or in the microwave in short intervals. Spread the melted chocolate over the top of the cornflake mixture.',
    'Refrigerate the dish for at least 2 hours, or until the bars are firm and the chocolate is set.',
    'Once set, cut the bars into squares or rectangles and serve. Store in an airtight container in the fridge for up to a week.',
  ],
  notes:
    'For added texture, you can replace some of the cashews with chopped dried fruits like raisins or cranberries. Adjust the sweetness by adding more or less maple syrup. For a nut-free option, swap out the peanut butter for sunflower seed butter and omit the cashews.',
};
