export const rootVegetableStew = {
  name: 'Root Vegetable Stew',
  param: 'root-vegetable-stew',
  recipeImage: 'assets/images/root-vegetable-stew.jpg',
  star: false,
  introText:
    'This hearty root vegetable stew is a comforting and wholesome meal packed with nutrients and earthy flavors.',
  description:
    'Root Vegetable Stew is a flavorful blend of potatoes, celery root, carrots, and parsnips simmered with red lentils in a seasoned broth. The stew has a savory and slightly tangy flavor profile, enriched by garlic and herbs like oregano. It’s a simple, filling, and nutritious meal that’s easy to prepare and perfect for cozy dinners.',
  category: ['main', 'soup'],
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Potato',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Root celery',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrot',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Parsnip',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red lentils',
      amount: 1,
      unit: 'cup',
      flex: 'Faux meat or beans.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1500,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 3,
      unit: 'cubes',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dried oregano',
      amount: 1,
      unit: 'tbsp',
      flex: 'Dried thyme, dried rosemary, or dried basil.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili',
      amount: 1,
      unit: 'tbsp',
      flex: 'Hot sauce, chili flakes, or chili paste.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any vinegar.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sourcream',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Dice the potatoes, root celery, carrots, and parsnips into bite-sized pieces. Peel the vegetables if necessary.',
    'In a large pot, combine the diced vegetables, water, and bouillon. Bring to a boil over medium-high heat.',
    'Reduce the heat and simmer for 10 minutes.',
    'Stir in the lentils, ketchup, white pepper, dried oregano, chili (if using), and vinegar. Let it simmer for another 10 minutes to allow the flavors to meld.',
    'If you’d like a richer flavor, optionally serve with finely chopped garlic mixed with sour cream on top.',
    'Taste and adjust the seasoning as needed before serving.',
  ],
  notes:
    'This stew is versatile—you can swap out any root vegetables or add beans and faux meat for extra protein. For added depth, try roasting the vegetables before adding them to the pot. Adjust the spice level by increasing or decreasing the amount of chili or opting for a milder alternative.',
};
