export const scallionSesameWaffles = {
  name: 'Scallion Sesame Waffles',
  param: 'scallion-sesame-waffles',
  recipeImage: 'assets/images/waffles.jpg',
  star: false,
  introText: 'These waffles are infused with fresh scallion and toasted sesame flavors for a savory twist.',
  description:
    'A twist on our classic waffles, featuring a dash of sesame oil, loaded with fresh spring onions, aromatic five-spice powder, white pepper and crunchy sesame seeds. Perfect for a savory breakfast or brunch.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    { name: 'Butter', amount: 40, unit: 'g', flex: '', optional: false, topping: false, done: false },
    { name: 'Sugar', amount: 20, unit: 'g', flex: '', optional: true, topping: false, done: false },
    { name: 'Salt', amount: 0.25, unit: 'tsp', flex: '', optional: false, topping: false, done: false },
    { name: 'Flour', amount: 80, unit: 'g', flex: '', optional: false, topping: false, done: false },
    { name: 'Baking powder', amount: 0.25, unit: 'tsp', flex: '', optional: false, topping: false, done: false },
    { name: 'Milk', amount: 1, unit: 'cup', flex: '', optional: false, topping: false, done: false },
    { name: 'Sesame oil', amount: 2, unit: 'tsp', flex: '', optional: false, topping: false, done: false },
    { name: 'Spring onion', amount: 3, unit: '', flex: '', optional: false, topping: false, done: false },
    { name: '5 spice powder', amount: 0.5, unit: 'tsp', flex: '', optional: false, topping: false, done: false },
    { name: 'White pepper', amount: 0.25, unit: 'tsp', flex: '', optional: false, topping: false, done: false },
    { name: 'Sesame seeds', amount: 1, unit: 'tbsp', flex: '', optional: false, topping: false, done: false },
  ],
  instructions: [
    'In a medium-sized bowl, whisk together the flour, baking powder, sugar, and salt.',
    'In a small saucepan or microwave-safe bowl, melt the vegan butter and let it cool slightly.',
    'In a separate bowl, mix the melted butter, plant-based milk, sesame oil, chopped spring onion, 5 spice powder, white pepper, and sesame seeds until well combined.',
    'Gradually pour the wet ingredients into the dry ingredients, whisking until a smooth batter forms. Be careful not to overmix.',
    'Preheat your waffle iron according to the manufacturer’s instructions.',
    'Lightly grease the waffle iron with oil or vegan butter if necessary.',
    'Pour an appropriate amount of batter onto the waffle iron and cook until golden brown and crispy, following your waffle maker’s guidelines.',
    'Carefully remove the waffles and repeat with the remaining batter.',
    'Serve warm with your favorite toppings like maple syrup or a sprinkle of extra sesame seeds.',
  ],
  notes: 'For a crispier texture, allow the waffles to cool on a wire rack for a few minutes before serving.',
};
