export const spongeCake = {
  name: 'Sponge Cake',
  param: 'sponge-cake',
  recipeImage: 'assets/images/sponge-cake.jpg',
  star: false,
  introText:
    'This light and fluffy sponge cake is perfect for any occasion. Whether enjoyed plain or layered with fillings, it’s a simple yet delicious treat.',
  description:
    'This sponge cake is soft, airy, and easy to make with just a few pantry staples. Using a combination of dairy-free milk, yogurt, and oil, it achieves a moist texture without the need for eggs. Perfect as a base for layered cakes, cupcakes, or simply enjoyed on its own with a dusting of powdered sugar.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.125,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yogurt',
      amount: 50,
      unit: 'g',
      flex: 'Milk or buttermilk',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line a cake tin with parchment paper.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and the white sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the yogurt, brown sugar, oil, and milk. Whisk until smooth (but no worries if there are some brown sugar lumps, just leave them be).',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared dish or ramekins.',
    'Bake for 18 minutes if using small muffin ramekins, 20 min if using large muffin ramekins, and 30 min if using a 20 x 20 cm dish, or until a toothpick inserted into the center comes out clean.',
    'Allow the cake to cool in the tin for 5 minutes before transferring it to a wire rack to cool completely.',
  ],
  notes:
    'For one serving of this recipe, a round 20 x 20 cm dish is ideal, or muffin ramekins. For added flavor, consider incorporating vanilla extract or lemon zest into the batter. This sponge cake can also be used as a base for layered cakes or cupcakes. Store in an airtight container or bag at room temperature for up to 3 days, or refrigerate for longer freshness. Can also be frozen. If mixing in berries like blueberries or strawberries, add up to 100g. This replaces the 50g of yogurt. Or if making banana or apple sauce muffins, replace the yogurt at a 1:1 ratio. Sprinkle sugar on top for a sweet, crusty surface.',
};
