export const taquitos = {
  name: 'Bean Tacos',
  param: 'taquitos',
  recipeImage: 'assets/images/taquitos.jpg',
  star: false,
  introText: 'Crispy, flavorful, and perfect for dipping, these tacos make a delicious snack or main dish.',
  description:
    'These vegan taquitos are stuffed with a spicy black bean filling and served with homemade guacamole. They’re easy to make, packed with protein, and bursting with flavor. Perfect for a quick meal or as party appetizers!',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Black beans',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Jalapeno',
      amount: 1,
      unit: '',
      flex: 'pickled jalapeno',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Curry seasoning',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime juice',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tortillas',
      amount: 3,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan cheese',
      amount: '',
      unit: '',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: '',
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Avocado',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red onion',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a food processor, combine the black beans, garlic, jalapeno, salt, curry powder, cumin, and lime juice. Process until smooth.',
    'Heat a large skillet over medium heat. Lightly warm the tortillas one at a time until pliable if stiff, about 10-15 seconds per side.',
    'Spread a few tablespoons of the black bean mixture onto each tortilla, leaving a small border around the edges. If desired, sprinkle vegan cheese on top of the filling.',
    'Roll each tortilla tightly around the filling to form a taquito, or simply fold it in half.',
    'Return the skillet to medium heat and add a small amount of oil. Place the taquitos seam-side down in the skillet and cook until golden and crispy on all sides, rotating as needed, about 2-3 minutes per side.',
    'While the taquitos are cooking, make the guacamole by mashing together the avocado, finely chopped red onion, and chopped tomatoes in a bowl. Season with salt to taste.',
    'Serve the taquitos hot with a side of guacamole and optional cilantro as garnish.',
  ],
  notes: 'Serve with your favorite salsa or vegan sour cream for even more flavor!',
};
