export const thaiGreenCurry = {
  name: 'Thai Green Curry',
  param: 'thai-green-curry',
  recipeImage: 'assets/images/thai-green-curry.jpg',
  star: false,
  introText: 'This Thai green curry is a fragrant and vibrant dish packed with fresh veggies.',
  description:
    'A comforting, aromatic Thai green curry made with creamy coconut milk, fresh vegetables, chickpeas, and the distinctive taste of Thai basil and lime. This easy-to-make vegan curry is perfect for a quick weeknight meal while delivering a delicious burst of flavor in every bite.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: 1,
      unit: 'serving',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coconut milk',
      amount: 1.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon cubes',
      amount: 2,
      unit: 'cubes',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Green curry paste',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bell pepper',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Zucchini',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Thai basil',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cook the rice according to package instructions and set aside.',
    'In a large pot, combine the coconut milk, water, and vegetable bouillon cubes over medium heat. Stir until the bouillon cubes are fully dissolved.',
    'Add the green curry paste to the pot and stir well to combine with the coconut milk mixture.',
    'Chop the bell pepper, scallions, and zucchini into bite-sized pieces. Add them to the pot along with the chickpeas.',
    'Simmer the curry for about 10-12 minutes until the vegetables are tender but still vibrant.',
    'Stir in the sugar and Thai basil, and let the curry simmer for another 2-3 minutes.',
    'Squeeze the juice of one lime into the curry, and stir well to incorporate.',
    'Taste and adjust the seasoning as needed—add more lime juice, sugar, or curry paste depending on your flavor preference.',
    'Serve the green curry hot over rice, and garnish with extra Thai basil or lime wedges if desired.',
  ],
  notes:
    'This Thai green curry is versatile, so feel free to add more vegetables like broccoli or snap peas. If you want more heat, add some sliced chili peppers. Thai basil brings a unique flavor to the dish, but if unavailable, you can substitute regular basil or cilantro for a different twist. The curry will keep in the fridge for up to 3 days and can be reheated for a quick meal.',
};
