export const tteokbokki = {
  name: 'Tteokbokki',
  param: 'tteokbokki',
  recipeImage: 'assets/images/tteokbokki.jpg',
  star: false,
  introText: 'Tteokbokki brings the fiery-sweet flavors of Korean street food to your table.',
  description:
    'This tteokbokki is the perfect blend of chewy rice cakes and a spicy, sweet, and savory sauce. Add your favorite vegetables, mushrooms, or tofu for a filling and satisfying meal that comes together in just 30 minutes.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Rice cakes (tteok)',
      amount: 500,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 2,
      unit: 'cups',
      flex: 'Any vegetable broth',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochujang',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochugaru',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown rice syrup',
      amount: 2,
      unit: 'tbsp',
      flex: 'Any syrup',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 3,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Napa cabbage',
      amount: '',
      unit: '',
      flex: 'Bok choy, zucchini, or any leafy greens',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Mushrooms',
      amount: '100',
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Firm tofu',
      amount: '100',
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'If rice cakes are refrigerated or frozen, soak them in warm water for 10-15 minutes to soften. Drain before cooking.',
    'In a large, shallow pan or skillet, combine water (or vegetable broth), vegan gochujang, soy sauce, maple syrup, and minced garlic. Whisk until the gochujang is fully dissolved. Adjust sweetness, salt, or spice levels to taste. For extra heat, add gochugaru if desired.',
    'Add sliced onion and any optional vegetables or mushrooms to the pan. Bring the mixture to a gentle boil over medium heat and let the vegetables soften for 3-4 minutes.',
    'Add the rice cakes to the pan. Stir occasionally to prevent sticking. Cook for 5-7 minutes until the rice cakes are soft and chewy, and the sauce thickens to a glossy consistency.',
    'If using tofu or tofu puffs, add them to the pan and heat through. Toss in scallion greens right before finishing to retain their color and freshness.',
    'Drizzle sesame oil over the top for added depth. Garnish with toasted sesame seeds before serving. Adjust seasoning as needed and enjoy hot.',
  ],
  notes:
    'Tteokbokki is incredibly versatile—feel free to add your favorite vegetables, mushrooms, or plant-based proteins. Serve with vegan kimchi or pickled radish for a tangy crunch. For those sensitive to heat, reduce the amount of gochujang or omit gochugaru altogether.',
};
